title: Drakiat's Blog
author: Drakiat
email: drakiatt@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Security research, tech and other interests.
theme: minima

# social links
#twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  Drakiat # DO NOT include the @ character, or else the build will fail!
url: https://drakiat.github.io/
baseurl: /
permalink: pretty
rss: RSS
show_excerpts: true # set to false to remove excerpts on the homepage
